version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    image: localhost/pbl4_devcontainer-app
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oposiciones
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
      MYSQL_HOST: db
    volumes:
      - ..:/workspace:cached,Z
      - venv-cache:/home/ubuntu/.venv:Z
      - m2-cache:/home/ubuntu/.m2:Z
      - npm-cache:/home/ubuntu/.npm:Z
    ports:
      - "8080:8080"
      - "3000:3000"
      - "8888:8888"
    depends_on:
      - db

  db:
    image: docker.io/mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: oposiciones
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql:Z

volumes:
  db-data:
  m2-cache:
  npm-cache:
  venv-cache:

